<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Mural extends \Entities\Mural implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function getAssunto()
    {
        $this->__load();
        return parent::getAssunto();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getMensagem()
    {
        $this->__load();
        return parent::getMensagem();
    }

    public function getDataCadastro()
    {
        $this->__load();
        return parent::getDataCadastro();
    }

    public function getDataSaiNovo()
    {
        $this->__load();
        return parent::getDataSaiNovo();
    }

    public function getDataExclusao()
    {
        $this->__load();
        return parent::getDataExclusao();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getIpUsuario()
    {
        $this->__load();
        return parent::getIpUsuario();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function setAssunto($assunto)
    {
        $this->__load();
        return parent::setAssunto($assunto);
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function setMensagem($mensagem)
    {
        $this->__load();
        return parent::setMensagem($mensagem);
    }

    public function setDataCadastro(\DateTime $dataCadastro)
    {
        $this->__load();
        return parent::setDataCadastro($dataCadastro);
    }

    public function setDataSaiNovo(\DateTime $dataSaiNovo)
    {
        $this->__load();
        return parent::setDataSaiNovo($dataSaiNovo);
    }

    public function setDataExclusao(\DateTime $dataExclusao)
    {
        $this->__load();
        return parent::setDataExclusao($dataExclusao);
    }

    public function setStatus(\Entities\Status $status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setIpUsuario($ipUsuario)
    {
        $this->__load();
        return parent::setIpUsuario($ipUsuario);
    }

    public function __set($property, $value)
    {
        $this->__load();
        return parent::__set($property, $value);
    }

    public function __call($method, $value)
    {
        $this->__load();
        return parent::__call($method, $value);
    }

    public function setAll(array $data)
    {
        $this->__load();
        return parent::setAll($data);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nome', 'assunto', 'email', 'mensagem', 'dataCadastro', 'dataSaiNovo', 'dataExclusao', 'ipUsuario', 'status');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}