<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Pessoa extends \Entities\Pessoa implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getPerfil()
    {
        $this->__load();
        return parent::getPerfil();
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function getLogin()
    {
        $this->__load();
        return parent::getLogin();
    }

    public function getSenha()
    {
        $this->__load();
        return parent::getSenha();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getTelefone()
    {
        $this->__load();
        return parent::getTelefone();
    }

    public function getDataCadastro()
    {
        $this->__load();
        return parent::getDataCadastro();
    }

    public function getDataExclusao()
    {
        $this->__load();
        return parent::getDataExclusao();
    }

    public function getDataNascimento()
    {
        $this->__load();
        return parent::getDataNascimento();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getCartaoMembro()
    {
        $this->__load();
        return parent::getCartaoMembro();
    }

    public function getFotoPessoa()
    {
        $this->__load();
        return parent::getFotoPessoa();
    }

    public function getCpf()
    {
        $this->__load();
        return parent::getCpf();
    }

    public function getCidadeNatal()
    {
        $this->__load();
        return parent::getCidadeNatal();
    }

    public function getRua()
    {
        $this->__load();
        return parent::getRua();
    }

    public function getBairro()
    {
        $this->__load();
        return parent::getBairro();
    }

    public function getCidade()
    {
        $this->__load();
        return parent::getCidade();
    }

    public function getRg()
    {
        $this->__load();
        return parent::getRg();
    }

    public function getOrgaoEmissor()
    {
        $this->__load();
        return parent::getOrgaoEmissor();
    }

    public function getDataEmissao()
    {
        $this->__load();
        return parent::getDataEmissao();
    }

    public function getFuncaoMinisterial()
    {
        $this->__load();
        return parent::getFuncaoMinisterial();
    }

    public function getProfissao()
    {
        $this->__load();
        return parent::getProfissao();
    }

    public function getEscolaridade()
    {
        $this->__load();
        return parent::getEscolaridade();
    }

    public function getEstadoCivil()
    {
        $this->__load();
        return parent::getEstadoCivil();
    }

    public function getDataChegada()
    {
        $this->__load();
        return parent::getDataChegada();
    }

    public function getDataBatismoAguas()
    {
        $this->__load();
        return parent::getDataBatismoAguas();
    }

    public function getDataBatismoEspirito()
    {
        $this->__load();
        return parent::getDataBatismoEspirito();
    }

    public function getNomePai()
    {
        $this->__load();
        return parent::getNomePai();
    }

    public function getNomeMae()
    {
        $this->__load();
        return parent::getNomeMae();
    }

    public function getNomeConjuge()
    {
        $this->__load();
        return parent::getNomeConjuge();
    }

    public function getDataCasamento()
    {
        $this->__load();
        return parent::getDataCasamento();
    }

    public function getQtdFilhos()
    {
        $this->__load();
        return parent::getQtdFilhos();
    }

    public function getDepartamentos()
    {
        $this->__load();
        return parent::getDepartamentos();
    }

    public function setPerfil(\Entities\Perfil $perfil)
    {
        $this->__load();
        return parent::setPerfil($perfil);
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function setLogin($login)
    {
        $this->__load();
        return parent::setLogin($login);
    }

    public function setSenha($senha)
    {
        $this->__load();
        return parent::setSenha($senha);
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function setTelefone($telefone)
    {
        $this->__load();
        return parent::setTelefone($telefone);
    }

    public function setDataCadastro(\DateTime $dataCadastro)
    {
        $this->__load();
        return parent::setDataCadastro($dataCadastro);
    }

    public function setDataExclusao(\DateTime $dataExclusao)
    {
        $this->__load();
        return parent::setDataExclusao($dataExclusao);
    }

    public function setDataNascimento(\DateTime $dataNascimento)
    {
        $this->__load();
        return parent::setDataNascimento($dataNascimento);
    }

    public function setStatus(\Entities\Status $status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setCartaoMembro($cartaoMembro)
    {
        $this->__load();
        return parent::setCartaoMembro($cartaoMembro);
    }

    public function setFotoPessoa($fotoPessoa)
    {
        $this->__load();
        return parent::setFotoPessoa($fotoPessoa);
    }

    public function setCpf($cpf)
    {
        $this->__load();
        return parent::setCpf($cpf);
    }

    public function setCidadeNatal($cidadeNatal)
    {
        $this->__load();
        return parent::setCidadeNatal($cidadeNatal);
    }

    public function setRua($rua)
    {
        $this->__load();
        return parent::setRua($rua);
    }

    public function setBairro($bairro)
    {
        $this->__load();
        return parent::setBairro($bairro);
    }

    public function setCidade($cidade)
    {
        $this->__load();
        return parent::setCidade($cidade);
    }

    public function setRg($rg)
    {
        $this->__load();
        return parent::setRg($rg);
    }

    public function setOrgaoEmissor($orgaoEmissor)
    {
        $this->__load();
        return parent::setOrgaoEmissor($orgaoEmissor);
    }

    public function setDataEmissao($dataEmissao)
    {
        $this->__load();
        return parent::setDataEmissao($dataEmissao);
    }

    public function setFuncaoMinisterial(\Entities\FuncaoMinisterial $funcaoMinisterial)
    {
        $this->__load();
        return parent::setFuncaoMinisterial($funcaoMinisterial);
    }

    public function setProfissao(\Entities\Profissao $profissao)
    {
        $this->__load();
        return parent::setProfissao($profissao);
    }

    public function setEscolaridade(\Entities\Escolaridade $escolaridade)
    {
        $this->__load();
        return parent::setEscolaridade($escolaridade);
    }

    public function setEstadoCivil(\Entities\EstadoCivil $estadoCivil)
    {
        $this->__load();
        return parent::setEstadoCivil($estadoCivil);
    }

    public function setDataChegada($dataChegada)
    {
        $this->__load();
        return parent::setDataChegada($dataChegada);
    }

    public function setDataBatismoAguas($dataBatismoAguas)
    {
        $this->__load();
        return parent::setDataBatismoAguas($dataBatismoAguas);
    }

    public function setDataBatismoEspirito($dataBatismoEspirito)
    {
        $this->__load();
        return parent::setDataBatismoEspirito($dataBatismoEspirito);
    }

    public function setNomePai($nomePai)
    {
        $this->__load();
        return parent::setNomePai($nomePai);
    }

    public function setNomeMae($nomeMae)
    {
        $this->__load();
        return parent::setNomeMae($nomeMae);
    }

    public function setNomeConjuge($nomeConjuge)
    {
        $this->__load();
        return parent::setNomeConjuge($nomeConjuge);
    }

    public function setDataCasamento($dataCasamento)
    {
        $this->__load();
        return parent::setDataCasamento($dataCasamento);
    }

    public function setQtdFilho($qtdFilhos)
    {
        $this->__load();
        return parent::setQtdFilho($qtdFilhos);
    }

    public function setDepartamentos($departamentos)
    {
        $this->__load();
        return parent::setDepartamentos($departamentos);
    }

    public function getGenero()
    {
        $this->__load();
        return parent::getGenero();
    }

    public function setGenero($genero)
    {
        $this->__load();
        return parent::setGenero($genero);
    }

    public function setQtdFilhos($qtdFilhos)
    {
        $this->__load();
        return parent::setQtdFilhos($qtdFilhos);
    }

    public function __set($property, $value)
    {
        $this->__load();
        return parent::__set($property, $value);
    }

    public function __call($method, $value)
    {
        $this->__load();
        return parent::__call($method, $value);
    }

    public function setAll(array $data)
    {
        $this->__load();
        return parent::setAll($data);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'genero', 'nome', 'login', 'senha', 'email', 'telefone', 'dataCadastro', 'dataExclusao', 'dataNascimento', 'cartaoMembro', 'fotoPessoa', 'cpf', 'cidadeNatal', 'rua', 'bairro', 'cidade', 'rg', 'orgaoEmissor', 'dataEmissao', 'dataChegada', 'dataBatismoAguas', 'dataBatismoEspirito', 'nomePai', 'nomeMae', 'nomeConjuge', 'dataCasamento', 'qtdFilhos', 'departamentos', 'perfil', 'status', 'funcaoMinisterial', 'profissao', 'escolaridade', 'estadoCivil');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}