<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Noticia extends \Entities\Noticia implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getTitulo()
    {
        $this->__load();
        return parent::getTitulo();
    }

    public function getDescricao()
    {
        $this->__load();
        return parent::getDescricao();
    }

    public function getSubTitulo()
    {
        $this->__load();
        return parent::getSubTitulo();
    }

    public function getFonte()
    {
        $this->__load();
        return parent::getFonte();
    }

    public function getFotoNoticia()
    {
        $this->__load();
        return parent::getFotoNoticia();
    }

    public function getFotoNoticiaPequena()
    {
        $this->__load();
        return parent::getFotoNoticiaPequena();
    }

    public function getDataCadastro()
    {
        $this->__load();
        return parent::getDataCadastro();
    }

    public function getDataSaiNovo()
    {
        $this->__load();
        return parent::getDataSaiNovo();
    }

    public function getDepartamento()
    {
        $this->__load();
        return parent::getDepartamento();
    }

    public function getPessoaCadastro()
    {
        $this->__load();
        return parent::getPessoaCadastro();
    }

    public function getTipo()
    {
        $this->__load();
        return parent::getTipo();
    }

    public function getDataExclusao()
    {
        $this->__load();
        return parent::getDataExclusao();
    }

    public function getPessoaExclusao()
    {
        $this->__load();
        return parent::getPessoaExclusao();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getPerfil()
    {
        $this->__load();
        return parent::getPerfil();
    }

    public function getPath()
    {
        $this->__load();
        return parent::getPath();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setTitulo($titulo)
    {
        $this->__load();
        return parent::setTitulo($titulo);
    }

    public function setDescricao($descricao)
    {
        $this->__load();
        return parent::setDescricao($descricao);
    }

    public function setSubTitulo($subTitulo)
    {
        $this->__load();
        return parent::setSubTitulo($subTitulo);
    }

    public function setFonte($fonte)
    {
        $this->__load();
        return parent::setFonte($fonte);
    }

    public function setFotoNoticia($fotoNoticia)
    {
        $this->__load();
        return parent::setFotoNoticia($fotoNoticia);
    }

    public function setFotoNoticiaPequena($fotoNoticiaPequena)
    {
        $this->__load();
        return parent::setFotoNoticiaPequena($fotoNoticiaPequena);
    }

    public function setDataCadastro(\DateTime $dataCadastro)
    {
        $this->__load();
        return parent::setDataCadastro($dataCadastro);
    }

    public function setDataSaiNovo(\DateTime $dataSaiNovo)
    {
        $this->__load();
        return parent::setDataSaiNovo($dataSaiNovo);
    }

    public function setDepartamento(\Entities\Departamento $departamento)
    {
        $this->__load();
        return parent::setDepartamento($departamento);
    }

    public function setPessoaCadastro(\Entities\Pessoa $pessoaCadastro)
    {
        $this->__load();
        return parent::setPessoaCadastro($pessoaCadastro);
    }

    public function setTipo(\Entities\TipoNoticia $tipo)
    {
        $this->__load();
        return parent::setTipo($tipo);
    }

    public function setDataExclusao(\DateTime $dataExclusao)
    {
        $this->__load();
        return parent::setDataExclusao($dataExclusao);
    }

    public function setPessoaExclusao(\Entities\Pessoa $pessoaExclusao)
    {
        $this->__load();
        return parent::setPessoaExclusao($pessoaExclusao);
    }

    public function setStatus(\Entities\Status $status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setPerfil(\Entities\Perfil $perfil)
    {
        $this->__load();
        return parent::setPerfil($perfil);
    }

    public function setPath($path)
    {
        $this->__load();
        return parent::setPath($path);
    }

    public function __set($property, $value)
    {
        $this->__load();
        return parent::__set($property, $value);
    }

    public function __call($method, $value)
    {
        $this->__load();
        return parent::__call($method, $value);
    }

    public function setAll(array $data)
    {
        $this->__load();
        return parent::setAll($data);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titulo', 'descricao', 'subTitulo', 'fonte', 'fotoNoticia', 'fotoNoticiaPequena', 'dataCadastro', 'dataSaiNovo', 'dataExclusao', 'path', 'departamento', 'pessoaCadastro', 'tipo', 'pessoaExclusao', 'status', 'perfil');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}